# Generated by Django 5.2.8 on 2025-11-09 05:31

import django.db.models.deletion
import utilities.product_images_path
import utilities.products_default_description
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default=utilities.products_default_description.product_default_description)),
                ('measure', models.SmallIntegerField()),
                ('unit', models.CharField(choices=[('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('t', 'Tonne'), ('ml', 'Milliliter'), ('l', 'Liter'), ('m3', 'Cubic Meter'), ('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('km', 'Kilometer'), ('in', 'Inch'), ('ft', 'Foot'), ('yd', 'Yard'), ('pc', 'Piece'), ('dz', 'Dozen'), ('pr', 'Pair')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('TK', 'Taka'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to=utilities.product_images_path.ProductImagePath)),
                ('category', models.ForeignKey(default='Others', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='categories.category')),
            ],
        ),
    ]
