# Generated by Django 5.2.8 on 2025-11-09 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=5),
        ),
        migrations.AddField(
            model_name='product',
            name='second_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
