# Generated by Django 5.2.8 on 2025-11-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_marks_product_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='marks',
            new_name='tags',
        ),
    ]
