# Generated by Django 5.2.8 on 2025-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('TK', 'Taka'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee')], default='TK', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('t', 'Tonne'), ('ml', 'Milliliter'), ('l', 'Liter'), ('m3', 'Cubic Meter'), ('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('km', 'Kilometer'), ('in', 'Inch'), ('ft', 'Foot'), ('yd', 'Yard'), ('pc', 'Piece'), ('dz', 'Dozen'), ('pr', 'Pair')], default='kg', max_length=10),
        ),
    ]
