# Generated by Django 5.2.8 on 2025-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_currency_alter_product_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='second_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
