# Generated by Django 5.2.8 on 2025-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_offered_amount_product_offered_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offered_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='offered_count_unit',
            field=models.CharField(choices=[('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('t', 'Tonne'), ('ml', 'Milliliter'), ('l', 'Liter'), ('m3', 'Cubic Meter'), ('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('km', 'Kilometer'), ('in', 'Inch'), ('ft', 'Foot'), ('yd', 'Yard'), ('pc', 'Piece'), ('dz', 'Dozen'), ('pr', 'Pair')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offered_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='offered_amount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
