# Generated by Django 5.2.8 on 2025-11-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_offer_product_offer_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
