# Generated by Django 5.2.8 on 2025-11-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_offer_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offered_amount',
        ),
    ]
